# Generated by Django 4.2.8 on 2023-12-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(max_length=500, null=True)),
                ('origin_url', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
